# .streamlit/config.toml

[theme]
base="light"  # Change to light mode
primaryColor="#4CAF50"  # Soft green for buttons and highlights
backgroundColor="#F9F9F9"  # Light background for the app
secondaryBackgroundColor="#FFFFFF"  # Slightly darker background for containers
textColor="#333333"  # Dark gray for text to reduce harshness on eyes
